name: Daily Scraper Check

on:
  workflow_dispatch: # للتشغيل اليدوي
  schedule:
    - cron: '0 6 * * *' # يعمل الساعة 9:00 صباحاً بتوقيت سوريا/السعودية (GMT+3)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # صلاحية ضرورية لتحديث ملف الذاكرة تلقائياً
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install requests pandas openpyxl pyTelegramBotAPI

      - name: Run Scraping Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} # التأكد من تطابق الاسم مع الـ Secrets والكود
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python Scraping.py

      - name: Save Data State
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add knowledge_base.json
          git commit -m "Update Local Data Base" || exit 0
          git push || exit 0
